name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      TEST: ENV_VALUE
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1

      - name: PoW
        if: ${{ env.TEST == 'ENV_VALUE' }}
        run: echo "Hello $FIRST_NAME $middle_name $Last_Name, today is Monday!"
        env:
          FIRST_NAME: ${{ secrets.COVID_API }}
          middle_name: The
          Last_Name: Octocat

      - name: Create env File
        shell: bash
        env:
          COVID_API: ${{ secrets.COVID_AP }}
        run: |
          touch .env
          echo COVID_API="$COVID_API" >> .env
          cat .env

      - name: Install and Build ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run tailwind
          npm run build

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
